### ISSUE TITLE
VPS doesn't start after first boot to NixOS

### ISSUE THREAD

**Issue by xddxdd** [zhaofengli/nixos-openvz#1]
Hi, I'm seeing a strange issue with my OpenVZ 7 VPS. When I make a tarball of my NixOS configuration, deploy it to my VPS, and reboot, it boots properly on the first time to NixOS. Then, if I ever reboot it again (either with or without deploying the same configuration to it), the VPS will not come up again. It shows up as "Offline" in SolusVM, and booting or restarting has no effect.

Do you have any suggestions on where I can check? So far I've tried:

1. Set up an OpenVZ 7 node myself and deploy the same configuration to a VPS on it: the VPS starts normally on every reboot.
2. Checking contents of `/bin/bash` and `/sbin/init` before reboot: the contents seem normal, `/bin/bash` calls bash in Nix store after the `vzctl` check, and `/sbin/init` points to the init script of my NixOS config.

The provider in question is EthernetServers.

**Comment by zhaofengli** [comment]
Interesting. The first boot is where the [first-time-init script](https://github.com/zhaofengli/nixos-openvz/blob/a2eae2624ae9d317ac2e18c6b3c3f6403aea1287/installer.nix#L3-L51) will move all existing files into `/old-root`. So maybe one of the provider commands is trying to run something other than `/bin/bash` which won't be there the next boot.

Could you try changing the first-time-init script to only `rm -rf /etc` (otherwise the existing stuff there will cause systemd to crash) but not perform `lustrateRoot`? Does the machine continue to boot after the booting into NixOS the first time?

I couldn't reproduce my initial failures on my own OpenVZ 7 node either, so I think the forced scripts might be something from SolusVM which I wasn't in the mood to set up myself. Getting any visibility into what was actually going on was therefore a huge pain.

<details>
<summary>Very ugly debugging method (my apologies)</summary>

If you don't mind getting your hands dirty, the way I got any visibility was to call the Telegram Bot API to send me messages from the init script and the `/bin/bash` wrapper. It looks something like this:

```bash
      # set up networking
      ip link set venet0 up
      ip a a 10.10.0.233/32 dev venet0
      ip r a default dev venet0

      log () {
        >>/boot-log echo "printing to log: $1"
        curl -k --get -H "Host: api.telegram.org" "https://149.154.167.220/XXXX/sendMessage?chat_id=XXX" --data-urlencode "text=$1" >> /boot-log 2>&1 &
      }

      log "invoked /bin/bash $@, PID is $$, PATH is $PATH, environment is $(env), ps auxw is $(ps auxw)"
```
</details>

**Comment by xddxdd** [comment]
Problem found, the provider runs `/sbin/quotaon` on VPS startup. The problem no longer appears after I link `${pkgs.quota}/bin/quotaon` to `/sbin/quotaon`.

This seems to be a common way to set disk usage limits for OpenVZ VPSes, so I think we can add the file by default.

I will prepare a PR shortly.

**Comment by zhaofengli** [comment]
Hmm, it's a bit odd to depend on the guest to enable the limits, but OpenVZ is odd enough anyways 😅 My VPSes at Inception Hosting and Gullo's Hosting don't do that, and the disk limits are enforced.

PRs welcome!
